/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 08050503
 */
public class Adicionar_Especime extends javax.swing.JFrame {

    private int codigo;
    private Classes.Especime.Sexo sexo;
    private Especie especie;
    private int codigopad;

    /**
     * Creates new form Criar_Especime1
     */
    public Adicionar_Especime() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel9.setBackground(new java.awt.Color(206, 208, 45));
        jPanel9.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial Black", 2, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(139, 0, 0));
        jLabel11.setText("!");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(30, 10, 20, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 2, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(139, 0, 0));
        jLabel10.setText("!");
        jPanel9.add(jLabel10);
        jLabel10.setBounds(270, 10, 20, 30);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Nimbus Sans", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADICIONAR ESPÉCIME");
        jLabel3.setToolTipText("");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 200, 30);

        jPanel9.add(jPanel4);
        jPanel4.setBounds(60, 10, 200, 30);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(null);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        jButton2.setText("ADICIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(10, 10, 110, 30);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(null);
        jPanel6.add(jTextField1);
        jTextField1.setBounds(150, 130, 240, 30);
        jPanel6.add(jTextField2);
        jTextField2.setBounds(150, 10, 240, 30);
        jPanel6.add(jTextField3);
        jTextField3.setBounds(150, 50, 240, 30);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Nimbus Sans", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CODIGO PADDOCK");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel1);
        jLabel1.setBounds(10, 130, 130, 30);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Nimbus Sans", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CÓDIGO");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel2);
        jLabel2.setBounds(10, 10, 130, 30);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Nimbus Sans", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ESPÉCIE");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel4);
        jLabel4.setBounds(10, 50, 130, 30);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Nimbus Sans", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SEXO");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jLabel5);
        jLabel5.setBounds(10, 90, 130, 30);
        jPanel6.add(jTextField4);
        jTextField4.setBounds(150, 90, 240, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean status = true;
        String a = jTextField2.getText();
        this.codigo = Integer.parseInt(a);
        
        String s = jTextField3.getText();
        
        String t = jTextField1.getText();
        this.codigopad = Integer.parseInt(t);
        
        String r = jTextField4.getText();
        
        if (s.equals(Classes.Especie.APATOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.APATOSSAURO;
        }
        if (s.equals(Classes.Especie.BRAQUIOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.BRAQUIOSSAURO;
        }
        if (s.equals(Classes.Especie.COMPSOGNATO.getNomeEspecie())) {
            this.especie = Classes.Especie.COMPSOGNATO;
        }
        if (s.equals(Classes.Especie.DILOFOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.DILOFOSSAURO;
        }
        if (s.equals(Classes.Especie.EDMONTOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.EDMONTOSSAURO;
        }
        if (s.equals(Classes.Especie.ESTEGOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.ESTEGOSSAURO;
        }
        if (s.equals(Classes.Especie.GALIMIMO.getNomeEspecie())) {
            this.especie = Classes.Especie.GALIMIMO;
        }
        if (s.equals(Classes.Especie.MAMENQUISSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.MAMENQUISSAURO;
        }
        if (s.equals(Classes.Especie.MICROCERATOPO.getNomeEspecie())) {
            this.especie = Classes.Especie.MICROCERATOPO;
        }
        if (s.equals(Classes.Especie.PAQUICEFALOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.PAQUICEFALOSSAURO;
        }
        if (s.equals(Classes.Especie.PARASSAUROLOFO.getNomeEspecie())) {
            this.especie = Classes.Especie.PARASSAUROLOFO;
        }
        if (s.equals(Classes.Especie.PTERANODONTE.getNomeEspecie())) {
            this.especie = Classes.Especie.PTERANODONTE;
        }
        if (s.equals(Classes.Especie.TIRANOSSAURO.getNomeEspecie())) {
            this.especie = Classes.Especie.TIRANOSSAURO;
        }
        if (s.equals(Classes.Especie.TRICERATOPO.getNomeEspecie())) {
            this.especie = Classes.Especie.TRICERATOPO;
        }
        if (s.equals(Classes.Especie.VELOCIRAPTOR.getNomeEspecie())) {
            this.especie = Classes.Especie.VELOCIRAPTOR;
        }
        if (r.equals(Classes.Especime.Sexo.MACHO.getStringSexo())) {
            this.sexo = Classes.Especime.Sexo.MACHO;
        } else {
            this.sexo = Classes.Especime.Sexo.FEMEA;
        }

if(status){
        Classes.Especime e = new Classes.Especime(this.codigo, this.especie, this.sexo);
        Classes.EspecimeDAO.getInstance().adicionar(this.codigo, e);
        Classes.PaddockDAO.getInstance().AddEspecime(this.codigo, this.codigopad);
        dispose();
    }
else{
    JOptionPane.showMessageDialog(this, "Não foi possivel realizar a ação.", "ERRO", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jTextField4ActionPerformed() {

    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adicionar_Especime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adicionar_Especime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adicionar_Especime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adicionar_Especime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adicionar_Especime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
